source 'https://rubygems.org'

gem 'rails', '4.1.5'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'libv8'
gem 'less-rails'  
gem 'therubyracer'
gem 'twitter-bootstrap-rails'
gem 'activeadmin', github: 'activeadmin'
gem 'devise'
gem "paperclip", "~> 4.2"
gem 'rmagick', '2.13.2'
gem 'groupdate'
gem 'bootstrap-datepicker-rails'

